sudo: required
services:
  - docker
language: php
php:
  - 5.6
install:
  - composer update
script:
  - make test
cache:
  directories:
  - vendor
  - node_modules
notifications:
  slack:
    secure: QZzOgsVqg/sjputp+I5AMu1rtaRnKrQwOsSEcify+GPujI7M+ubZKcb/aMRAdBww+9xLwG1bdm6pWhNiUXqPJ54mnNaUgu67tptBJNwVzaF0QjYph4KeXqgQKnHNv626t17bilmE4xNULXHn7ekq444mH2R6uH9evWA9UkuvdvLUVwWWS0CcaJhKiXZHjT1KSbc9JLl6wV1LQVHVVE7zRvr7oXLNTFMpjVcx5fIEFq9vOa4cumzUFvUGD2v8vB3THz+QPHxxOSAd793SIp7wedScYJsxabeaBD13KiPHz750ijVdqeoJf+qgQ9xyJGmI7D7M562C7Bk7lf4gs+p+I7L9hX6swkzUA8H6E3KBoh1mG943NdagKDPBj7djeX5+m8nLgrCwDVdVFmrMm+IpY+e++9KtcAdJ0Kc2l2cIMWR8e1d5NXlwgZ+X8mDwsToxirKiSPKxd71Iz5WiIG1oO8ywBas2bYQyFDeCkUbLrEJh6DYhfp7Zb+61/Fo2bvo8gch9ELJFAFtbnd+fHRXbNRry8OzV6XfC9YbC89HX8vAPiuBrfQhSdEz0BMSyeQn33FPf+szn23Fmn/uO4DJX4Q1nZBTeBdF/qnTu9fdCDh8Ndll4sw7grRKsMKhS89OqAI786AogfbWLIpJqKUXyGA2byFWj2zPPp4ehBpYtJvc=
