sudo: required
services:
  - docker
  - npm
language: php
php:
  - 5.6
before_install:
    - sudo apt-get install n
    - sudo n 4.2.1
install:
  - npm install
  - composer update
script:
  - make test
cache:
  directories:
  - vendor
  - node_modules
